[package]
name = "cex"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
klang = {path = "../"}
phf = { version = "0.11.3", features = ["macros"] }
tokio = { version = "1.43.0", features = ["full"] }
